# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://elevendusks.com/"
relativeURLs = true
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

assetDir = "assets"
module = { imports = [ { path = "github.com/jpanther/congo/v2" } ] }

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

[params]
  [params.color]
    theme = "blue"